### ISSUE TITLE
How to get an array of points with some step inside a multipolygon?

### ISSUE THREAD

**Issue by Astraport** [songjiahong/Geo.Library#15]
![8yyut](https://user-images.githubusercontent.com/1259709/161572207-50c8ecfa-ffd9-4fcd-8f50-b7b307935170.png)

I need to collect points inside the city like in the picture. It would be possible to use a loop within a loop, but there is no IsPointInside method for MultiPolygon.
What can you advise?

**Comment by songjiahong** [comment]
Add a method in multipolygon to check whether point is inside.
