### ISSUE TITLE
Exception in FromGeoJson method 

### ISSUE THREAD

**Issue by itsmebhaskar** [songjiahong/Geo.Library#4]
Geometry.FromGeoJson("{\"type\":\"Polygon\",\"coordinates\":[[[-116.91831289341842,33.80555255143657],[-116.91841633121251,33.805675783408368],[-116.91874037901931,33.806024127169117],[-116.91908451448822,33.806358777119115],[-116.91944790862698,33.806678926893085],[-116.91982968575134,33.8069838048609],[-116.92022892634249,33.807272676595289],[-116.92064466853866,33.8075448460154],[-116.92107591068576,33.807799657280825],[-116.92152161375124,33.808036496373077],[-116.92198070382858,33.808254792576314],[-116.92245207472602,33.8084540198537],[-116.92293459063343,33.80863369811609],[-116.92342708886098,33.808793394379784],[-116.9239283826425,33.808932723810948],[-116.92443726399753,33.809051350653654],[-116.92495250664454,33.809148989039819],[-116.92547286895831,33.809225403678631],[-116.92599709696478,33.809280410424115],[-116.92652392736544,33.80931387671928],[-116.92705209058457,33.809325721915869],[-116.92758031383148,33.809315917468908],[-116.92810732417081,33.809284487005492],[-116.92863185159274,33.809231506267871],[-116.9291
5263207655,33.809157102930726],[-116.92966841063955,33.809061456293193],[-116.93017794436382,33.808944796846383],[-116.93068000539435,33.808807405717474],[-116.93117338390009,33.80864961399157],[-116.93165689099172,33.808471801913242],[-116.93212936158879,33.808274397969306],[-116.93258965722892,33.808057877855454],[-116.93303666881289,33.807822763328993],[-116.93346931927846,33.807569620950446],[-116.93388656619688,33.807299060717305],[-116.9342874042854,33.807011734592962],[-116.93467086783009,33.806708334934505],[-116.93503603301293,33.806389592823216],[-116.93538202013751,33.806056276301739],[-116.93570799574813,33.805709188522208],[-116.93591387483396,33.805466311236415],[-116.928495,33.804944],[-116.928501,33.805765],[-116.92632,33.805702],[-116.919448,33.805539],[-116.91831289341842,33.80555255143657]]],\"bbox\":[-116.93591387483396,33.804944,-116.91831289341842,33.809325721915869]}"
)

Exception
Invalid Json! Expect ']' but '44'

**Comment by songjiahong** [comment]
The reason of the failure is the bbox is not supported right now. Try to remove that part and it will work. The current geojson we support is actually part of the geojson - the geometry member in geojson (check [RFC7964](https://tools.ietf.org/html/rfc7946) for detail). The bbox member should be the same level as geometry instead of inside the geometry.
