### ISSUE TITLE
How to check if a point is in a Multipolygon

### ISSUE THREAD

**Issue by meyumeapps** [songjiahong/Geo.Library#8]
Hi,

Do you have any thoughts on how I can use the library to check if a point is within a multipolygon?

Thanks
Scott

**Comment by songjiahong** [comment]
You can go through each polygon in the multipolygon and check whether the point is in the polygon with the function `Polygon.IsPointInside(Point point)`

**Comment by meyumeapps** [comment]
Thanks I will give that a go.

I think I might have to take into account this sort of multi polygon though [outer and inner](https://wiki.openstreetmap.org/wiki/File:Multipolygon_Illustration_1.svg)

**Comment by daniel-rck** [comment]
@meyumeapps The outer-inner case is correctly handled (see https://github.com/songjiahong/Geo.Library/blob/fabac710ed507689712789910c450df76b25db60/GeoLibrary.Unit/Operation.Facts/PointFacts.cs#L202). So if you check each point in a loop, the issue could be resolved.

**Comment by songjiahong** [comment]
Add a method in multipolygon to check whether point is inside.
