### ISSUE TITLE
Polygon.FromGeoJson() does not return à Polygon

### ISSUE THREAD

**Issue by abouroubi** [songjiahong/Geo.Library#9]
When we are sure that the GeoJSON is a Polygon, and use Polygon.FromGeoJson() the returned object is Geometry instead of Polygon.

How can we get around that ?

**Comment by songjiahong** [comment]
Can you provide the detail of the GeoJSON? The function `FromGeoJson` itself will always return a Geometry object, you can try to cast to a Polygon if it is

**Comment by abouroubi** [comment]
Ok, I will cast it, I was thinking that `Polygon.FromGeoJson()`will return a Polygon.
